### PR TITLE
Upgrade to embedded-graphics 0.7

### PR DESCRIPTION
**Pull request by jamwaffles**
embedded-graphics 0.7 was just released with some major changes in how fonts work. This PR updates `ibm437` to e-g 0.7.

I've added a debugger "example" which, at time of writing, renders the fonts like this:

image

I'm not sure if this is correct, but please tell me if it isn't and I'll tweak the font configs to make the font look the same as the e-g 0.6 code.

### CODE REVIEW

**Comment by sbechet** [comment]
Hello James,

Thank you very much but I can't directly merge your pull request because conflicting files.
Do you want to send me a new version or can i commit manually your work?

**Comment by jamwaffles** [comment]
Huh, maybe some strange rebase badness happened and I didn't notice. I've fixed the conflicts now, sorry about that!

**Comment by sbechet** [comment]
Hello James,

[crates uploaded](https://crates.io/crates/ibm437)

**Comment by jamwaffles** [comment]
Awesome! Thanks for the quick release :)

**Pull request merged**
